using System;
using System.Reflection;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.5448
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyTitleAttribute("NHibernate.DomainModel")]
[assembly: AssemblyDescriptionAttribute("The Domain Model used by the Unit Tests.")]
[assembly: AssemblyCompanyAttribute("NHibernate.org")]
[assembly: AssemblyProductAttribute("NHibernate.DomainModel")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("3.2.1.4000")]
[assembly: AssemblyInformationalVersionAttribute("3.2.1.4000")]
[assembly: AssemblyFileVersionAttribute("3.2.1.4000")]
[assembly: AssemblyDelaySignAttribute(false)]

